version: '3'

services:
  database_prod:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
    - db-volume:/var/lib/postgresql/data

  api_prod:
    image: lelesd2m2s10/praticando-api
    environment:
      DB_HOST: database_prod
    ports:
      - "8181:9090"
volumes:
  db-volume: